# https://projecteuler.net/problem=2

# Even Fibonacci numbers

'''
Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence 
whose values do not exceed four million, 
find the sum of the even-valued terms.
'''

# Make a Fibonacci sequence
# Keep if mod2
# sum


def Problem2(n):
	a = 0
	b = 1
	fib = [] 

	while b < n:
		a, b = b, a+b
		if b<n and b%2==0: 
			fib.append(b)

	return sum(fib)



print(Problem2(5)) #2 
print(Problem2(4000000))

